log:
  level: "info"
  filename: "./logs/web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "1.1.1.1"
  user: "root"              # 用户名
  password: "123456"          # 密码
  db: "todolist"
  Port: "3306"
  max_open_conns: 10
  max_idle_conns: 5

email:
  addr: "smtp.qq.com:25"
  identity: ""
  username: "1111111@qq.com"  # 发送方的邮箱
  password: "授权码"         # 邮箱的授权码
  host: "smtp.qq.com"

redis:
  host: "1.1.1.1"
  password: ""
  db : 0
  port : 60379
  pool_size: 100


